config:
  target: 'http://localhost:3000'
  processor: './artillery-processor.cjs'

  phases:
  - duration: 240
    arrivalRate: 100
    rampTo: 200
    name: 'Ramp up to high traffic'
  - duration: 360
    arrivalRate: 200
    name: 'Sustained high traffic'
  - duration: 240
    arrivalRate: 200
    rampTo: 0
    name: 'Ramp down from high traffic'

scenarios:
  - name: 'Get page of questions'
    flow:
      #  - loop:
      - get:
          url: '/qa/questions?product_id=45006'

