config:
  target: 'http://localhost:3000'
  processor: './artillery-processor.cjs'

  phases:
  - duration: 60
    arrivalRate: 20
    rampTo: 100
    name: 'Ramp up to high traffic'
  - duration: 300
    arrivalRate: 100
    name: 'Sustained high traffic'

scenarios:
  - name: 'Get page of questions'
    flow:
      #  - loop:
      - get:
          url: '/qa/questions?product_id=45006'

